export const SELECT_CLIENT = 'SELECT_CLIENT';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const SELECT_INVOICE = 'SELECT_INVOICE';
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';

export const FETCH_INVOICE = 'FETCH_INVOICE';
export const FETCH_INVOICE_SUCCESS = 'FETCH_INVOICE_SUCCESS';
export const FETCH_INVOICE_FAILURE = 'FETCH_INVOICE_FAILURE';

export const CHANGE_ITEM_AMOUNT = 'CHANGE_ITEM_AMOUNT';
export const CHANGE_ITEM_DETAIL = 'CHANGE_ITEM_DETAIL';
export const DELETE_ITEM = 'DELETE_ITEM';

export const ADD_ITEM_TO_INVOICE = 'ADD_ITEM_TO_INVOICE';

